from .headerMD import *
from .aboutMD import *
from .achievmentsMD import *
from .contactMD import *
from .offersMD import *
from .planMD import *
from .projectsMD import *
from .psMD import *
from .servicesMD import *