# Generated by Django 5.1.2 on 2024-12-06 16:48

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1_uz', ckeditor.fields.RichTextField(verbose_name='about text1 uz')),
                ('text1_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='about text1 ru')),
                ('text1_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='about text1 en')),
                ('text2_uz', ckeditor.fields.RichTextField(verbose_name='about text2 uz')),
                ('text2_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='about text2 ru')),
                ('text2_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='about text2 en')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_images/', verbose_name='about image')),
            ],
        ),
        migrations.CreateModel(
            name='AboutHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='header title uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title en')),
            ],
            options={
                'verbose_name': 'About Header',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', ckeditor.fields.RichTextField(verbose_name='achievment soni')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='achievment nomi uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='achievment nomi ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='achievment nomi en')),
            ],
            options={
                'verbose_name': 'achievment',
            },
        ),
        migrations.CreateModel(
            name='AchievementsHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='header title uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title en')),
            ],
            options={
                'verbose_name': 'achievements header',
            },
        ),
        migrations.CreateModel(
            name='ContactHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='header title uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title en')),
            ],
            options={
                'verbose_name': 'Contact Header',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uz', ckeditor.fields.RichTextField(verbose_name='question uz')),
                ('question_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='question ru')),
                ('question_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='question en')),
                ('answer_uz', ckeditor.fields.RichTextField(verbose_name='answer uz')),
                ('answer_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='answer ru')),
                ('answer_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='answer en')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_uz', ckeditor.fields.RichTextField(verbose_name='Footer matni uz')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Footer matni ru')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Footer matni en')),
                ('copyright_text_uz', ckeditor.fields.RichTextField(verbose_name='Copyrigth text uz')),
                ('copyright_text_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Copyrigth text ru')),
                ('copyright_text_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Copyrigth text en')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footerlar',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='title uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='title ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='title en')),
                ('text1_uz', ckeditor.fields.RichTextField(verbose_name='text1 uz')),
                ('text1_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='text1 ru')),
                ('text1_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='text1 en')),
                ('text2_uz', ckeditor.fields.RichTextField(verbose_name='text2 uz')),
                ('text2_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='text2 ru')),
                ('text2_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='text2 en')),
                ('image', models.ImageField(blank=True, null=True, upload_to='header_images/', verbose_name='header image')),
            ],
            options={
                'verbose_name': 'Header',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='offers_icons/', verbose_name='offer icon')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='offer title uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='offer title ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='offer title en')),
                ('description_uz', ckeditor.fields.RichTextField(verbose_name='offer description uz')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='offer description ru')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='offer description en')),
            ],
        ),
        migrations.CreateModel(
            name='OffersHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='header title uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title en')),
            ],
            options={
                'verbose_name': 'offers header',
            },
        ),
        migrations.CreateModel(
            name='OurSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ijtimoiy tarmoq nomi')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='our_social_media/', verbose_name='icon file')),
                ('url', models.CharField(max_length=500, verbose_name='Ijtimoiy tarmoq urlini kiriting')),
            ],
            options={
                'verbose_name': 'Ijtimoiy Tarmoqlarimiz',
                'verbose_name_plural': 'Ijtimoiy Tarmoqlarimiz',
            },
        ),
        migrations.CreateModel(
            name='PlanHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='header title uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title en')),
            ],
            options={
                'verbose_name': 'plan header',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='muammo uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='muammo rus')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='muammo eng')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='project title uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='project title ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='project title en')),
                ('subtitle_uz', ckeditor.fields.RichTextField(verbose_name='project subtitle uz')),
                ('subtitle_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='project subtitle ru')),
                ('subtitle_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='project subtitle en')),
                ('description_uz', ckeditor.fields.RichTextField(verbose_name='project description uz')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='project description ru')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='project description en')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='project photo')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectsHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='header title uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title en')),
            ],
            options={
                'verbose_name': 'Projects Header',
            },
        ),
        migrations.CreateModel(
            name='PSHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='header title uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title en')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='ps_icons/', verbose_name='ps icon')),
            ],
            options={
                'verbose_name': 'problem&solution header',
            },
        ),
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ism')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Xabarlar(Message)',
                'verbose_name_plural': 'Xabarlar(Messages)',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='service title uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='service title ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='service title en')),
                ('description_uz', ckeditor.fields.RichTextField(verbose_name='service description uz')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='service description ru')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='service description en')),
            ],
            options={
                'verbose_name': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServicesHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='header title uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='header title en')),
            ],
            options={
                'verbose_name': 'services header',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='plan_step_icons/', verbose_name='step icon')),
                ('title_uz', ckeditor.fields.RichTextField(verbose_name='step title uz')),
                ('title_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='step title ru')),
                ('title_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='step title en')),
                ('description_uz', ckeditor.fields.RichTextField(verbose_name='step description uz')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='step description ru')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='step description en')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_uz', ckeditor.fields.RichTextField(verbose_name='yechim uz')),
                ('solution_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='yechim rus')),
                ('solution_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='yechim eng')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='main.problem', verbose_name='problem')),
            ],
        ),
    ]
